// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {store} from '../models';
import {screenresolution} from '../models';

export function Context():Promise<context.Context>;

export function GetConfig():Promise<store.Config>;

export function ScreenResolution():Promise<screenresolution.Resolution>;

export function ScreenScale():Promise<number>;
