// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {frontend} from '../models';

export function OpenDirectory(arg1:frontend.OpenDialogOptions):Promise<string>;

export function ShowErrorDialog(arg1:string):Promise<void>;
