// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {file} from '../models';

export function BathRename(arg1:Array<file.FileInfo>,arg2:string):Promise<void>;

export function ErrorLog(arg1:Error):Promise<void>;

export function GetFilesInfo(arg1:string):Promise<Array<file.FileInfo>>;

export function ReadFile(arg1:string):Promise<string>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;

export function ZipFolder(arg1:file.ZipConfig):Promise<void>;
