// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Dir(arg1) {
  return window['go']['path']['Path']['Dir'](arg1);
}

export function PathExists(arg1) {
  return window['go']['path']['Path']['PathExists'](arg1);
}
