// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Dir(arg1:string):Promise<string>;

export function PathExists(arg1:string):Promise<boolean>;
